# Generated by Django 2.1.5 on 2019-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_id', models.PositiveIntegerField()),
                ('cafe_keyword', models.CharField(max_length=30)),
            ],
        ),
    ]
